name: GitHub README Activity Section Updater
description: Updates your personal README with the recent GH activity, fork of https://github.com/jamesgeorge007/github-activity-readme.
author: MadeByThePinsHub

inputs:
  GH_USERNAME:
    description: 'Your GitHub username'
    default: ${{ github.repository_owner }}
    required: false
  COMMIT_MSG:
    description: "Commit message used while committing to the repo"
    default: ":zap: Update README with the recent activity"
    required: false
  MAX_LINES:
    description: "The maximum number of lines populated in your readme file"
    default: 5
    required: false

branding:
  color: yellow
  icon: activity

runs:
  using: node14
  main: dist/index.js
